"use client";

import { themeToVars } from "@mantine/vanilla-extract";
import { get, mapValues } from "lodash";
import { semanticToMantineMap } from "@src/styles/tokens/semantic";
import { baseTheme } from "@src/styles/tokens/mantine";

const mantineVars = themeToVars(baseTheme);

const semanticToMantineCategory = {
  accents: "colors",
  surfaces: "colors",
  categorical: "colors",
  functionals: "colors",
  dataviz: "colors",
  radius: "radius",
  shadows: "shadows",
};

/**
 * Map semantic values to CSS variable values generated by Mantine
 *
 * @example
 * vars.semantic.categorical.activity
 * // -> "var(--colors-categorical-3)"
 */
// @ts-expect-error - weird mapping
const semanticVars = mapValues(
  semanticToMantineMap,
  (value: string, key: keyof typeof semanticToMantineMap) =>
    mapValues(value, (semanticValue) =>
      get(mantineVars, `${semanticToMantineCategory[key]}.${semanticValue}`)
    )
) as typeof semanticToMantineMap;

export const vars = {
  ...mantineVars,
  semantic: semanticVars,
};
